CREATE OR REPLACE DATABASE FOMC_ROBERTA;
CREATE OR REPLACE SCHEMA FOMC_SCHEMA;
CREATE OR REPLACE WAREHOUSE TEST_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 2 SCALING_POLICY = 'STANDARD';